spring:
  boot:
    admin:
      client:
        instance:
          name: manager-app
          service-host-type: ip
        url: http://localhost:8085
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: JwByKV4Y8m95GDYTNqJH6jfaj5dXpv8F
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: QddTu2SVo3TxukQ1lJSbe8fFt6hJ1wUq
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
selMag:
  service:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak