server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: 8waoWd3s5nSFJCPpSvSsfQSxkh3zpZoP
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: 8waoWd3s5nSFJCPpSvSsfQSxkh3zpZoP
            authorization-grant-type: client_credentials
            scope:
              - discovery
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'