spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: admin-service
            client-secret: a6b2da2e-771a-458b-922e-91df814258cb
            authorization-grant-type: client_credentials
            scope:
              - metrics
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: a6b2da2e-771a-458b-922e-91df814258cb
            scope:
              - metrics
              - openid
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: a6b2da2e-771a-458b-922e-91df814258cb
            authorization-grant-type: client_credentials
            scope:
              - discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/