spring:
  cloud:
    config:
      server:
        git:
          uri: git repository
          clone-on-start: true
          default-label: master(branch)
          search-paths:
            - '{application}/{profile}'